# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[(b'cm', b'Construction Materials'), (b'hd', b'Home Decor'), (b'ea', b'Electronic Appliances'), (b'ad', b'Art and Decorations'), (b'f', b'Furniture'), (b'bm', b'Bed Materials'), (b'kt', b'Kitchen Tools'), (b'b', b' Bookase'), (b'dw', b'Drawer'), (b'c', b'Cabinetry'), (b'd', b'Dressers'), (b'mo', b'Microwave Oven'), (b'r', b'Refrigerators'), (b'vc', b' Vaccum Cleaner'), (b'gf', b'Gas Fireplace'), (b'sp', b'Smart Phones')], max_length=1, null=True),
        ),
    ]
